### ISSUE TITLE
Aborted due to warnings

### ISSUE THREAD

**Issue by SAYConnected** [ederribeiro/generator-apu-codeigniter#1]
Hi i try your generator with NVM and NPM 0.10.36 On mac OS X 10.10.2
its failed look the log:

npm WARN package.json web@0.0.0 No repository field.
npm ERR! fetch failed https://registry.npmjs.org/extfs/-/extfs-0.0.7.tgz
npm ERR! Error: 400 Bad Request
npm ERR!     at WriteStream.<anonymous> (/Users/say-pro/.nvm/v0.10.36/lib/node_modules/npm/lib/utils/fetch.js:58:12)
npm ERR!     at WriteStream.emit (events.js:117:20)
npm ERR!     at evalmachine.<anonymous>:1610:14
npm ERR!     at /Users/say-pro/.nvm/v0.10.36/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:108:15)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 14.1.0
npm ERR! command "/Users/say-pro/.nvm/v0.10.36/bin/node" "/Users/say-pro/.nvm/v0.10.36/bin/npm" "install"
npm ERR! cwd /Users/say-pro/Documents/coditest-2
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0

**Comment by ederribeiro** [comment]
Hi, thanks for your report.

the problem is fixed.

Please try again, if possible: npm update -g generator-apu-codeigniter
