### ISSUE TITLE
CodeIgniter 3

### ISSUE THREAD

**Issue by CodingPeak** [ederribeiro/generator-apu-codeigniter#3]
Hi, I assume this uses CodeIgniter version 2.x? Why not upgrade it to use CodeIgniter 3?

**Comment by ederribeiro** [comment]
Yeah, the used version is 2.x.
I will update as soon i can.
Thanks.

**Comment by ederribeiro** [comment]
@Rubenvanhoeyveld up to date!

Thanks!
